name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          # 🔑 use the exact secret name Azure created for THIS SWA
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_MOSS_09F0C371E }}
          action: upload
          app_location: "/"     # index.html is at repo root
          api_location: ""      # no API
          output_location: ""   # EMPTY => do not look for build output
          skip_app_build: true  # 🚫 Oryx/Node build


